import type { Room } from "./types"

export const mockRooms: Room[] = [
  {
    id: "1",
    name: "Ocean View Suite",
    type: "suite",
    price: 450,
    rating: 4.9,
    reviews: 127,
    images: [
      "/placeholder.svg?height=300&width=400&text=Ocean+View+Suite",
      "/placeholder.svg?height=300&width=400&text=Ocean+View+Suite+2",
      "/placeholder.svg?height=300&width=400&text=Ocean+View+Suite+3",
    ],
    amenities: ["Ocean View", "Balcony", "WiFi", "Air Conditioning", "Mini Bar", "Room Service"],
    description: "Luxurious suite with breathtaking ocean views and premium amenities.",
    location: "Maldives",
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    size: 85,
  },
  {
    id: "2",
    name: "Deluxe Garden Room",
    type: "room",
    price: 320,
    rating: 4.7,
    reviews: 89,
    images: [
      "/placeholder.svg?height=300&width=400&text=Garden+Room",
      "/placeholder.svg?height=300&width=400&text=Garden+Room+2",
    ],
    amenities: ["Garden View", "WiFi", "Air Conditioning", "Mini Fridge", "Coffee Maker"],
    description: "Comfortable room overlooking beautiful tropical gardens.",
    location: "Bali",
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    size: 45,
  },
  {
    id: "3",
    name: "Family Suite",
    type: "suite",
    price: 580,
    rating: 4.8,
    reviews: 156,
    images: [
      "/placeholder.svg?height=300&width=400&text=Family+Suite",
      "/placeholder.svg?height=300&width=400&text=Family+Suite+2",
    ],
    amenities: ["Pool View", "Kitchenette", "WiFi", "Air Conditioning", "Sofa Bed", "Kids Area"],
    description: "Spacious suite perfect for families with children.",
    location: "Thailand",
    maxGuests: 6,
    bedrooms: 2,
    bathrooms: 2,
    size: 95,
  },
  {
    id: "4",
    name: "Presidential Suite",
    type: "suite",
    price: 950,
    rating: 5.0,
    reviews: 43,
    images: [
      "/placeholder.svg?height=300&width=400&text=Presidential+Suite",
      "/placeholder.svg?height=300&width=400&text=Presidential+Suite+2",
    ],
    amenities: ["Panoramic View", "Private Pool", "Butler Service", "WiFi", "Jacuzzi", "Wine Cellar"],
    description: "Ultimate luxury with private pool and butler service.",
    location: "Seychelles",
    maxGuests: 4,
    bedrooms: 3,
    bathrooms: 3,
    size: 150,
  },
  {
    id: "5",
    name: "Standard Room",
    type: "room",
    price: 220,
    rating: 4.5,
    reviews: 234,
    images: ["/placeholder.svg?height=300&width=400&text=Standard+Room"],
    amenities: ["WiFi", "Air Conditioning", "TV", "Mini Fridge"],
    description: "Comfortable and affordable accommodation with essential amenities.",
    location: "Philippines",
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    size: 35,
  },
  {
    id: "6",
    name: "Beachfront Villa",
    type: "villa",
    price: 750,
    rating: 4.9,
    reviews: 78,
    images: [
      "/placeholder.svg?height=300&width=400&text=Beachfront+Villa",
      "/placeholder.svg?height=300&width=400&text=Beachfront+Villa+2",
    ],
    amenities: ["Beach Access", "Private Pool", "Full Kitchen", "WiFi", "BBQ Area", "Parking"],
    description: "Exclusive beachfront villa with private pool and direct beach access.",
    location: "Fiji",
    maxGuests: 8,
    bedrooms: 4,
    bathrooms: 3,
    size: 200,
  },
]
