import type { Room } from "./types"

export const mockRooms: Room[] = [
  {
    id: "1",
    name: "Moorfield Villa - Ocean View Suite",
    type: "villa",
    price: 250,
    rating: 4.8,
    reviews: 124,
    images: [
      "/placeholder.svg?height=300&width=400&text=Ocean+View+Suite",
      "/placeholder.svg?height=300&width=400&text=Ocean+View+Bedroom",
      "/placeholder.svg?height=300&width=400&text=Ocean+View+Bathroom",
    ],
    amenities: [
      "Free parking",
      "Fast free WiFi (480 Mbps)",
      "Non-smoking rooms",
      "Laundry",
      "Tea/coffee maker in all rooms"
    ],
    description: "Luxurious suite with breathtaking ocean views and premium amenities.",
    location: "Maldives",
    max_guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    size: 45,
    available: true,
  },
  {
    id: "2",
    name: "Moorfield Villa - Deluxe Garden Room",
    type: "villa",
    price: 180,
    rating: 4.6,
    reviews: 89,
    images: [
      "/placeholder.svg?height=300&width=400&text=Garden+Room",
      "/placeholder.svg?height=300&width=400&text=Garden+View",
      "/placeholder.svg?height=300&width=400&text=Garden+Bathroom",
    ],
    amenities: [
      "Free parking",
      "Fast free WiFi (480 Mbps)",
      "Non-smoking rooms",
      "Laundry",
      "Tea/coffee maker in all rooms"
    ],
    description: "Comfortable room overlooking beautiful tropical gardens.",
    location: "Bali",
     max_guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    size: 35,
    available: true,
  },
  {
    id: "3",
    name: "Moorfield Villa - Family Suite",
    type: "villa",
    price: 320,
    rating: 4.9,
    reviews: 156,
    images: [
      "/placeholder.svg?height=300&width=400&text=Family+Suite",
      "/placeholder.svg?height=300&width=400&text=Family+Living+Room",
      "/placeholder.svg?height=300&width=400&text=Family+Bedroom",
    ],
    amenities: [
      "Free parking",
      "Fast free WiFi (480 Mbps)",
      "Non-smoking rooms",
      "Laundry",
      "Tea/coffee maker in all rooms"
    ],
    description: "Spacious suite perfect for families with separate living area.",
    location: "Thailand",
     max_guests: 4,
    bedrooms: 2,
    bathrooms: 2,
    size: 65,
    available: true,
  },
  {
    id: "4",
    name: "Moorfield Villa - Presidential Suite",
    type: "villa",
    price: 500,
    rating: 5.0,
    reviews: 78,
    images: [
      "/placeholder.svg?height=300&width=400&text=Presidential+Villa",
      "/placeholder.svg?height=300&width=400&text=Villa+Pool",
      "/placeholder.svg?height=300&width=400&text=Villa+Interior",
    ],
    amenities: [
      "Free parking",
      "Fast free WiFi (480 Mbps)",
      "Non-smoking rooms",
      "Laundry",
      "Tea/coffee maker in all rooms"
    ],
    description: "Ultimate luxury villa with private pool and dedicated butler service.",
    location: "Seychelles",
     max_guests: 6,
    bedrooms: 3,
    bathrooms: 3,
    size: 120,
    available: false,
  },
  {
    id: "5",
    name: "Moorfield Villa - Cozy Beach Cottage",
    type: "villa",
    price: 150,
    rating: 4.4,
    reviews: 92,
    images: [
      "/placeholder.svg?height=300&width=400&text=Beach+Cottage",
      "/placeholder.svg?height=300&width=400&text=Cottage+Interior",
      "/placeholder.svg?height=300&width=400&text=Beach+View",
    ],
    amenities: [
      "Free parking",
      "Fast free WiFi (480 Mbps)",
      "Non-smoking rooms",
      "Laundry",
      "Tea/coffee maker in all rooms"
    ],
    description: "Charming cottage just steps away from pristine white sand beach.",
    location: "Mauritius",
     max_guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    size: 30,
    available: true,
  },
  {
    id: "6",
    name: "Moorfield Villa - Mountain View Lodge",
    type: "villa",
    price: 220,
    rating: 4.7,
    reviews: 134,
    images: [
      "/placeholder.svg?height=300&width=400&text=Mountain+Lodge",
      "/placeholder.svg?height=300&width=400&text=Mountain+View",
      "/placeholder.svg?height=300&width=400&text=Lodge+Interior",
    ],
    amenities: [
      "Free parking",
      "Fast free WiFi (480 Mbps)",
      "Non-smoking rooms",
      "Laundry",
      "Tea/coffee maker in all rooms"
    ],
    description: "Rustic lodge with stunning mountain views and hiking trail access.",
    location: "Nepal",
     max_guests: 3,
    bedrooms: 1,
    bathrooms: 1,
    size: 40,
    available: true,
  },
]

export const popularAmenities = [
  "Free parking",
  "Fast free WiFi (480 Mbps)",
  "Non-smoking rooms",
  "Laundry",
  "Tea/coffee maker in all rooms"
]
