import type { Room, Villa } from "./types"

export const mockVillas: Villa[] = [
  {
    id: "1",
    name: "Moorfields Paradise Villa",
    description: "Luxury beachfront villa with stunning ocean views",
    location: "Maldives",
    address: "North Male Atoll, Maldives",
    amenities: ["Pool", "Beach Access", "WiFi", "Air Conditioning", "Restaurant"],
    images: ["/placeholder.svg?height=400&width=600&text=Villa+Paradise"],
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
]

export const mockRooms: Room[] = [
  {
    id: "1",
    villa_id: "1",
    name: "Ocean View Suite",
    description: "Spacious suite with panoramic ocean views and private balcony",
    price_per_night: 450,
    max_guests: 2,
    room_type: "Suite",
    size_sqm: 65,
    amenities: ["Ocean View", "Private Balcony", "King Bed", "Mini Bar", "WiFi"],
    images: ["/placeholder.svg?height=300&width=400&text=Ocean+View+Suite"],
    is_available: true,
    rating: 4.9,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    villa: mockVillas[0],
  },
  {
    id: "2",
    villa_id: "1",
    name: "Deluxe Garden Room",
    description: "Elegant room overlooking tropical gardens with modern amenities",
    price_per_night: 320,
    max_guests: 2,
    room_type: "Deluxe Room",
    size_sqm: 45,
    amenities: ["Garden View", "Queen Bed", "Air Conditioning", "WiFi", "Coffee Machine"],
    images: ["/placeholder.svg?height=300&width=400&text=Garden+Room"],
    is_available: true,
    rating: 4.7,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    villa: mockVillas[0],
  },
  {
    id: "3",
    villa_id: "1",
    name: "Family Suite",
    description: "Spacious family accommodation with separate living area",
    price_per_night: 580,
    max_guests: 4,
    room_type: "Family Suite",
    size_sqm: 85,
    amenities: ["Separate Living Area", "Two Bedrooms", "Kitchenette", "WiFi", "Pool Access"],
    images: ["/placeholder.svg?height=300&width=400&text=Family+Suite"],
    is_available: true,
    rating: 4.8,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    villa: mockVillas[0],
  },
  {
    id: "4",
    villa_id: "1",
    name: "Presidential Suite",
    description: "Ultimate luxury with private pool and butler service",
    price_per_night: 950,
    max_guests: 2,
    room_type: "Presidential Suite",
    size_sqm: 120,
    amenities: ["Private Pool", "Butler Service", "Ocean View", "Spa Bath", "Premium Amenities"],
    images: ["/placeholder.svg?height=300&width=400&text=Presidential+Suite"],
    is_available: true,
    rating: 5.0,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    villa: mockVillas[0],
  },
  {
    id: "5",
    villa_id: "1",
    name: "Standard Room",
    description: "Comfortable accommodation with essential amenities",
    price_per_night: 220,
    max_guests: 2,
    room_type: "Standard Room",
    size_sqm: 35,
    amenities: ["Double Bed", "Air Conditioning", "WiFi", "Private Bathroom"],
    images: ["/placeholder.svg?height=300&width=400&text=Standard+Room"],
    is_available: true,
    rating: 4.5,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    villa: mockVillas[0],
  },
  {
    id: "6",
    villa_id: "1",
    name: "Beachfront Villa",
    description: "Private villa directly on the beach with exclusive access",
    price_per_night: 750,
    max_guests: 6,
    room_type: "Villa",
    size_sqm: 150,
    amenities: ["Private Beach", "Full Kitchen", "Three Bedrooms", "Outdoor Dining", "WiFi"],
    images: ["/placeholder.svg?height=300&width=400&text=Beachfront+Villa"],
    is_available: true,
    rating: 4.9,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    villa: mockVillas[0],
  },
]
